language: php
php:
  - '7.3'
  - '7.2'
  - '7.1'
  - 5.6
  - 7.0
env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"
before_script:
  - composer self-update
  - composer install --no-interaction
script:
  - vendor/bin/phing
